[env:ttgo-lora32-v1]
platform = espressif32
board = ttgo-lora32-v1
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/Adafruit SSD1306 @ ^2.4.0
  adafruit/Adafruit GFX Library @ ^1.10.1
  olikraus/U8g2_for_Adafruit_GFX
  bblanchon/ArduinoJson @ ^6.21.0